### ISSUE TITLE
Issues using plex_autoscan_url.sh

### ISSUE THREAD

**Issue by ethanbayliss** [l3uddz/cloudbox#27]
Getting the following error when using the plex_autoscan_url.sh script. I realise this can be found without the script but it would probably give others issues too.

```
$ /opt/scripts/plex_autoscan/plex_autoscan_url.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 25 column 5 (char 878)
/opt/scripts/plex_autoscan/plex_autoscan_url.sh: line 5: [: =: unary operator expected
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 25 column 5 (char 878)
No Plex Autoscan token found.
http://:/
```
```
$ cat /opt/plex_autoscan/config/config.json
{
    "DOCKER_NAME": "plex",
    "PLEX_DATABASE_PATH": "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db",
    "PLEX_EMPTY_TRASH": true,
    "PLEX_EMPTY_TRASH_CONTROL_FILES": [
        "/mnt/unionfs/mounted.bin"
    ],
    "PLEX_EMPTY_TRASH_MAX_FILES": 100,
    "PLEX_EMPTY_TRASH_ZERO_DELETED": false,
    "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver",
    "PLEX_LOCAL_URL": "http://plex.redacted",
    "PLEX_SCANNER": "/usr/lib/plexmediaserver/Plex\\ Media\\ Scanner",
    "PLEX_SECTION_PATH_MAPPINGS": {
        "1": [
            "/Movies/"
        ],
        "2": [
            "/TV/"
        ]
    },
    "PLEX_SUPPORT_DIR": "/var/lib/plexmediaserver/Library/Application\\ Support",
    "PLEX_TOKEN": "redacted",
    "PLEX_USER": "plex",
    "PLEX_WAIT_FOR_EXTERNAL_SCANNERS": true,
    'PLEX_ANALYZE_FILE': false,
    "SERVER_ALLOW_MANUAL_SCAN": false,
    "SERVER_FILE_EXIST_PATH_MAPPINGS": {
        "/mnt/unionfs/Media": [
            "/data"
        ]
    },
    "SERVER_IP": "0.0.0.0",
    "SERVER_MAX_FILE_CHECKS": 10,
    "SERVER_PASS": "redacted",
    "SERVER_PATH_MAPPINGS": {
        "/data/Movies/": [
            "/movies/",
            "/unionfs/Media/Movies/"
        ],
        "/data/TV/": [
            "/tv/",
            "/unionfs/Media/TV/"
        ]
    },
    "SERVER_IGNORE_LIST": [
        "/.grab/",
        ".DS_Store",
        "Thumbs.db"
    ],
    "SERVER_USE_SQLITE": false,
    "SERVER_PORT": 3468,
    "SERVER_SCAN_DELAY": 5,
    "USE_DOCKER": true,
    "USE_SUDO": false
}
```
```
$ cat /opt/scripts/plex_autoscan/plex_autoscan_url.sh
#!/bin/bash

server_ip=$(cat /opt/plex_autoscan/config/config.json | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["'SERVER_IP'"]';)

if [ $server_ip = 0.0.0.0 ]; then
  plex_server_ip="$(curl -s http://checkip.amazonaws.com)"
else
  plex_server_ip=$server_ip
fi

port=$(cat /opt/plex_autoscan/config/config.json | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["'SERVER_PORT'"]';)

key=$(grep -m 1 "$port" /opt/plex_autoscan/plex_autoscan.log 2>/dev/null | sed 's:.*/::')

if [ -z "$key" ]; then
  i=1
  until [ "$key" ] || [ $i -gt 20 ]; do
    key=$(grep -m 1 "$port" /opt/plex_autoscan/plex_autoscan.log.$i 2>/dev/null | sed 's:.*/::')
    let i++
  done
  if [ -z "$key" ]; then
    echo "No Plex Autoscan token found."
    #exit 1
  fi
fi
```

**Comment by desimaniac** [comment]
You're config file needs fixing...

Change

```
    'PLEX_ANALYZE_FILE': false,
```

to 

```    
    "PLEX_ANALYZE_FILE": false,
```

**Comment by ethanbayliss** [comment]
@desimaniac Thanks mate, template was incorrect, see PR #28

**Comment by desimaniac** [comment]
NP.
